resources:
  - name: test_repo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: ~johns/step_samples

pipelines:
  - name: git_status
    steps:
      - name: execute_success_tests
        type: Bash
        configuration:
          inputResources:
            - name: test_repo

        execution:
          onStart:
            - update_commit_status test_repo
            - echo "$is_success"
          onExecute:
            - echo "hello world"
          onFailure:
            - echo "$is_success"
          onComplete:
            - echo "$is_success"
            - update_commit_status test_repo
      - name: execute_failure_tests
        type: Bash
        configuration:
          inputResources:
            - name: test_repo
          inputSteps:
            - name: execute_success_tests

        execution:
          onStart:
            - update_commit_status test_repo
            - echo "$is_success"
          onExecute:
            - cd fail
          onFailure:
            - echo "$is_success"
          onComplete:
            - echo "$is_success"
            - update_commit_status test_repo
