resources:
  - name: johns_jenkins_output
    type: PropertyBag
    configuration:
      jenkinsvalue: original

  - name: johns_jenkins_incomingHook
    type: IncomingWebhook
    configuration:
      webhookName: johns_incoming
  - name: johns_jenkins_outgoingHook
    type: OutgoingWebhook
    configuration:
      webhookName: johns_outgoing

pipelines:
  - name: john_jenkins_multibranch_support
    steps:
      - name: jenkinsStep
        type: Jenkins
        configuration:
          jenkinsJobName: blah
          jenkinsBranchName: {{gitBranch}}
          buildParameters:
            foo: bar
          integrations:
            - name: johns_ultra_new_jenkins
          # inputSteps:
          #   - name: firstStep
          outputResources:
            - name: johns_jenkins_output

  - name: john_jenkins_support
    steps:
      # - name: firstStep
      #   type: Bash
      #   execution:
      #     onExecute:
      #       - echo "hello"
      - name: jenkinsStep
        type: Jenkins
        configuration:
          jenkinsJobName: blah
          buildParameters:
            foo: bar
          integrations:
            - name: johns_ultra_new_jenkins
          # inputSteps:
          #   - name: firstStep
          outputResources:
            - name: johns_jenkins_output

      # - name: lastStep
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: johns_jenkins_output
      #   execution:
      #     onExecute:
      #       - printenv | grep johns_jenkins_output


  - name: johns_jenkins_fake
    steps:
      - name: fake_jenkins_job
        type: Bash
        configuration:
          inputResources:
            - name: johns_jenkins_incomingHook
          outputResources:
            - name: johns_jenkins_outgoingHook

        execution:
          onExecute:
            - echo "$johns_jenkins_incomingHook" | jq '.' > payload.json
            - cat payload.json
            - export stepId=$(read_json payload.json stepId)
            - set_payload "{\"action\":\"status\",\"stepId\":\"$stepId\"}"


