
resources:
  - name: sample_repo
    type: GitRepo
    configuration:
      path: trriplejay/step_samples
      gitProvider: github
      branches:
        include: ^master$

  - name: sample_simpleserver
    type: GitRepo
    configuration:
      gitProvider: github
      path: trriplejay/simpleserver
      branches:
        include: "^master$"

  - name: sample_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art

  - name: sample_spec
    type: FileSpec
    configuration:
      sourceArtifactory: art
      pattern: '*'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}


pipelines:
  - name: sample_buildapp
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: mbuild
        type: MvnBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: ${pipeline_name}_maven
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          integrations:
            - name: art
          inputResources:
            - name: sample_repo
          outputResources:
            - name: sample_info
            - name: sample_spec
          autoPublishBuildInfo: true


          mvnCommand: clean install


          sourceLocation: demos/Maven/sample-project


          resolverSnapshotRepo: maven-snapshot-remote


          deployerSnapshotRepo: maven-snapshot-local


          resolverReleaseRepo: maven-release-remote


          deployerReleaseRepo: maven-release-local

        execution:
          onSuccess:
            - write_output sample_spec buildName="${JFROG_CLI_BUILD_NAME}"
            - write_output sample_spec buildNumber="${JFROG_CLI_BUILD_NUMBER}"

      - name: dbuild
        type: DockerBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: ${pipeline_name}_docker
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          affinityGroup: docker
          dockerFileLocation: "."
          dockerFileName: Dockerfile
          dockerImageName: 192.168.56.2:8082/docker-local/simpleserver
          dockerImageTag: ${run_id}
          inputResources:
            - name: sample_simpleserver
            - name: sample_spec
              trigger: false
          integrations:
            - name: art

      - name: push
        type: DockerPush
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: ${pipeline_name}_docker
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          affinityGroup: docker
          inputSteps:
            - name: build
          integrations:
            - name: art


